name: testing_lutter
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^0.1.0
  random_words: "^1.0.1"
  fluro: "^1.3.1"
  flutter_map: ^0.0.1
  location: "^1.2.0"
  map_view: "^0.0.12"
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

